# Mathematics and Statistics Assignment 13

# Question 3

Write a program to obtain 7 samples of size n=5 from the housefly wing length population (given in assignment 8). Obtain the ANOVA table for these sample groups. 

In [14]:
import numpy as np
import plotly.graph_objects as go
from scipy.stats import kurtosis, skew
from scipy.stats import anderson
import random
import statistics
from prettytable import PrettyTable

In [2]:
# Reading Input

wingsHouseflies = []

with open("wings houseflies", "r") as f:
    wingsHouseflies = list(map(int,f.read().split()));

wing_mean = np.mean(wingsHouseflies)
wing_stdev = statistics.stdev(wingsHouseflies)
print(wingsHouseflies)
print(len(wingsHouseflies))

[36, 41, 42, 43, 45, 46, 47, 48, 49, 51, 37, 41, 42, 44, 45, 46, 47, 48, 49, 51, 38, 41, 42, 44, 45, 46, 47, 48, 49, 51, 38, 41, 43, 44, 45, 46, 47, 48, 49, 51, 39, 41, 43, 44, 45, 46, 47, 48, 50, 52, 39, 41, 43, 44, 45, 46, 47, 48, 50, 52, 40, 42, 43, 44, 45, 46, 47, 48, 50, 53, 40, 42, 43, 44, 45, 46, 47, 49, 50, 53, 40, 42, 43, 44, 45, 46, 47, 49, 50, 54, 40, 42, 43, 44, 45, 46, 48, 49, 50, 55]
100


In [4]:
# Sampling 7 samples of size 5 each

samples = []
for _ in range(35):
    samples.append(wingsHouseflies[random.randint(0,len(wingsHouseflies)-1)])

samples = np.asarray(samples).reshape((7,5))
print(samples)

[[45 48 46 44 50]
 [41 42 43 38 44]
 [51 46 46 40 42]
 [52 51 41 44 42]
 [48 46 42 44 42]
 [46 49 42 50 42]
 [48 55 46 44 42]]


In [24]:

a = 7
b = 5
T = np.sum(samples)
Tjdot = np.sum(samples, axis = 1)
sqSum = np.sum(np.square(samples))
TjdotSqSum = np.sum(np.square(Tjdot))

V = sqSum - (T**2)/(a*b)
Scap2 = V / (a*b-1) 
print("V: ",V)
print("DOF(V): ab-1: ",a*b-1)
print("Scap2: ", Scap2)
VB = TjdotSqSum/b - (T**2)/(a*b)
ScapB2 = VB / (a-1)
print("VB: ", VB)
print("DOF(VB): a-1: ",a-1)
print("ScapB2: ", ScapB2)
VW = V - VB
ScapW2 = VW / (a*(b-1))
print("VW: ", VW)
print("DOF(VW): a(b-1): ",a*(b-1))
print("ScapW2: ",ScapW2)
F = ScapB2 / ScapW2
df1 = a - 1
df2 = a*(b-1)
print("")
print("F: ", F)
print("df1: ", df1, " df2: ", df2)

x = PrettyTable()
x.field_names = ["Variation", "Degrees Of Freedom", "Mean Square", "F"]

x.add_row(["VB: "+str(VB), "a-1: "+str(a-1), "ScapB2: "+str(ScapB2), "F: "+str(F)])
x.add_row(["VW: "+str(VW), "a(b-1): "+str(a*(b-1)), "ScapW2: "+str(ScapW2)," with a-1: "+str(a-1)])
x.add_row(["V: "+str(V), "ab-1: "+str(a*b-1), "Scap2: "+ str(Scap2), "and a(b-1): "+str(a*(b-1))+" degrees of freedom"])

print(x)

V:  505.6000000000058
DOF(V): ab-1:  34
Scap2:  14.870588235294289
VB:  99.20000000001164
DOF(VB): a-1:  6
ScapB2:  16.533333333335275
VW:  406.3999999999942
DOF(VW): a(b-1):  28
ScapW2:  14.514285714285506

F:  1.1391076115487064
df1:  6  df2:  28
+-----------------------+--------------------+----------------------------+-----------------------------------+
|       Variation       | Degrees Of Freedom |        Mean Square         |                 F                 |
+-----------------------+--------------------+----------------------------+-----------------------------------+
| VB: 99.20000000001164 |       a-1: 6       | ScapB2: 16.533333333335275 |       F: 1.1391076115487064       |
| VW: 406.3999999999942 |     a(b-1): 28     | ScapW2: 14.514285714285506 |             with a-1: 6           |
|  V: 505.6000000000058 |      ab-1: 34      | Scap2: 14.870588235294289  | and a(b-1): 28 degrees of freedom |
+-----------------------+--------------------+----------------------------+----

In [7]:
sqSum

72012

In [17]:
str(F)

'1.1391076115487064'